trigger:
- main

pool:
  name: Default
  demands:
    - agent.name -equals bilout

variables:
  appName: 'testoch'
  azureSubscription: 'Azure for Students(a6b57087-18b9-45e4-bd4d-01991a1e0f25)'  # Remplace par le nom exact de ta connexion de service
  tempArchiveDir: '$(Build.ArtifactStagingDirectory)/archive-content'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'Install Dependencies'

- script: npm run test
  displayName: 'Run Jest tests'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/junit.xml'
    failTaskOnFailedTests: true
  displayName: 'Publish Results on Azure DevOps interface'

- script: npm run build
  displayName: 'Build the project'
  condition: succeeded() # Build si seulement les tests sont passés


# Prepare build to deploy : Copy only dist/ et package.json 
- script: |
    mkdir -p $(tempArchiveDir)
    cp -r dist $(tempArchiveDir)/
    cp package.json $(tempArchiveDir)/
  displayName: 'Prepare clean archive folder'

- task: ArchiveFiles@2
  inputs:
    #rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    rootFolderOrFile: '$(tempArchiveDir)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true
  displayName: 'Archive dist and package.json'
  condition: succeeded()  # Archive seulement si tout a réussi avant

- task: AzureRmWebAppDeployment@5
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: '$(azureSubscription)'
    appType: 'webAppLinux'
    WebAppName: '$(appName)'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/app.zip'
    DeploymentTypeLinux: 'oneDeploy'
  displayName: 'Deploy to Azure App Service'
  condition: succeeded()  # Déploie uniquement si tout a réussi (tests inclus)
